[theme.templates]
enable_builtin_templates = true
builtin_ids              = ["kcolorscheme", "btop","kitty", "hyprland", "helix"]        # opt-in; run: noctalia theme --list-templates
enable_community_templates = true
community_ids = ["discord", "yazi"]

